version: "3.5"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile_back
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    environment:
      - FRONT_URL=http://localhost
      - REDIS=redis
      - DB_USERNAME=testing_test
      - DB_PASSWORD=password123
      - DB_NAME=messages
      - DB_HOST=postgres
    depends_on: 
        - postgres
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - 5000:5000
    container_name: frontend
    environment:
      - API_URL=http://localhost/api
  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data
  postgres:
    image: postgres
    container_name: postgres
    volumes: 
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=testing_test
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=messages
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
        - backend
        - frontend
volumes:
    database:
