version: '3.5'

services: 
    backend:
        container_name: backend
        build: 
            context: .
            dockerfile: Dockerfile_back
        volumes:
            - type: bind
              source: ./logs.txt
              target: /usr/app/logs.txt
        environment:
            - FRONT_URL=http://localhost:8002
            - REDIS=redis
            - DB_USERNAME=ducky
            - DB_PASSWORD=yellow
            - DB_NAME=postgres_database
            - DB_HOST=db
        ports:
            - 8001:8000
        depends_on: 
            - db

    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: Dockerfile_front
        environment:
            - API_URL=http://localhost:8001
        ports:
            - 8002:5000
        depends_on: 
            - backend

    redis:
        container_name: redis
        image: redis

    db:
        container_name: db
        image: postgres
        restart: unless-stopped
        environment: 
            - POSTGRES_PASSWORD=yellow
            - POSTGRES_USER=ducky
            - POSTGRES_DB=postgres_database
        volumes: 
            - database:/var/lib/postgresql/data
volumes:
    database:
