name: 'Deploy to Heroku' #set whatevername you want to your github job
on:
  push:
    branches: 
      - master
       
      # set the events you would like to trigger this job
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Part3/ex2

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6  # use the latest version of the action
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.API_KEY }}
        run: heroku container:login
      - uses: akhileshns/heroku-deploy@v3.4.6  # use the latest version of the action
        with:
          appdir: Part3/ex2
          heroku_email: ${{ secrets.EMAIL_ACCOUNT }} # your heroku email
          heroku_api_key: ${{ secrets.API_KEY }} # your  heroku api key
          heroku_app_name: ${{ secrets.APP_NAME }} # you aplication name
          usedocker: true
          #dockerfile: 'C:\Users\camilla.colliander\dockercourse\Part3\ex2' # set the path to the folder wher the Dokerfile is located
         # options: '' # Docker Build Options


